### ISSUE TITLE
Update library to use new (supported) JSON API

### ISSUE THREAD

**Issue by smallsam** [smallsam/pymyair#1]
Advantage Air have at now released a public API which unfortunately deprecates the old XML based API that I was using.

This library is likely broken for all but those that have yet to update their MyAir tablet software.

I will migrate to the new JSON API so that we can get this working again

**Comment by lucasnetau** [comment]
Do you have any details on the JSON API? I asked the support team at AdvantageAir and I was just told it was available but no details on how to use it.

**Comment by speedst3r** [comment]
I have submitted PR#2 that utilises the new JSON API.

**Comment by smallsam** [comment]
Thanks to @speedst3r who wrote the json api implementation a couple of years ago now.
Re-visiting this api now it's nearly summer!
